db:
  username: ${username.value:admin}
  password: admin
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0.1
  properties:
    first: 123
    second: 567
    third.value: Third
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3

spring.profiles.active: qa

logging:
  level:
    root: INFO
    com.kornienko.spring.database.pool: INFO
    org.springframework.jdbc.core: TRACE
  file:
    name: kornienko.log
    path: /log/


spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    format:
      date: iso
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      batch_size: 50
      fetch_size: 50
      show_sql: true
      format_sql: true
      highlight_sql: true
      hbm2ddl.auto: validate
    open-in-view: false
  messages:
    basename: messages

app:
  common:
    logging:
      enabled: true
      level: INFO
